#pragma once
// gguf-weights.h: load model weights from GGUF files
//
// GGUF weight loader for all model components (LM, DiT, CondEncoder, TextEncoder, Detokenizer, VAE).
// All components use GGUF bf16 files generated by convert.py.
//
// Usage:
//   GGUFModel gf;
//   if (!gf_load(&gf, "model.gguf")) { error; }
//   WeightCtx wctx;
//   wctx_init(&wctx, n_tensors);
//   ggml_tensor * w = gf_load_tensor(&wctx, gf, "layer.0.weight");
//   wctx_alloc(&wctx, backend);
//   gf_close(&gf);   // safe after wctx_alloc copied data to GPU

#include "gguf.h"
#include "weight-ctx.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unordered_map>
#include <vector>

#ifdef _WIN32
#    include <windows.h>
#else
#    include <fcntl.h>
#    include <sys/mman.h>
#    include <sys/stat.h>
#    include <unistd.h>
#endif

// A tensor under the name the loaders ask for when the file names it
// otherwise: the llama.cpp style layout of the HOT-Step converter
// (scragnog/MiniMax-Music3-GGUF). The DiT's q, k and v are row ranges of its
// fused qkv there.
struct GGUFAlias {
    struct ggml_tensor * meta;  // canonical name, the shape a loader sees
    const void *         data;
};

struct GGUFModel {
    struct gguf_context *                      gguf;         // parsed header (KV + tensor metadata)
    struct ggml_context *                      meta;         // tensor descriptors (no data)
    struct ggml_context *                      alias_meta;   // descriptors of the aliases
    std::unordered_map<std::string, GGUFAlias> aliases;
    uint8_t *                                  mapping;      // mmapped file
    size_t                                     file_size;
    size_t                                     data_offset;  // gguf_get_data_offset(gguf)
#ifdef _WIN32
    HANDLE fh;
    HANDLE mh;
#else
    int fd;
#endif
};

static void gf_close(GGUFModel * gf) {
    if (gf->gguf) {
        gguf_free(gf->gguf);
    }
    if (gf->meta) {
        ggml_free(gf->meta);
    }
    if (gf->alias_meta) {
        ggml_free(gf->alias_meta);
    }
#ifdef _WIN32
    if (gf->mapping) {
        UnmapViewOfFile(gf->mapping);
    }
    if (gf->mh) {
        CloseHandle(gf->mh);
    }
    if (gf->fh && gf->fh != INVALID_HANDLE_VALUE) {
        CloseHandle(gf->fh);
    }
#else
    if (gf->mapping) {
        munmap(gf->mapping, gf->file_size);
    }
    if (gf->fd >= 0) {
        close(gf->fd);
    }
#endif
    *gf = {};
}

// The canonical names of one tensor of a HOT-Step layout file, with the row
// part each takes (-1 the whole tensor, 0..2 the q, k or v third)
static void gf_hotstep_names(const std::string & name, std::vector<std::pair<std::string, int>> * out) {
    auto starts = [&](const char * prefix, std::string * rest) {
        size_t n = strlen(prefix);
        if (name.compare(0, n, prefix) != 0) {
            return false;
        }
        *rest = name.substr(n);
        return true;
    };
    // "N.tail" -> N, tail
    auto layer = [](const std::string & rest, std::string * idx, std::string * tail) {
        size_t dot = rest.find('.');
        if (dot == std::string::npos || dot == 0) {
            return false;
        }
        for (size_t i = 0; i < dot; i++) {
            if (rest[i] < '0' || rest[i] > '9') {
                return false;
            }
        }
        *idx  = rest.substr(0, dot);
        *tail = rest.substr(dot + 1);
        return true;
    };
    auto map_tail = [](const std::string & tail, const std::vector<std::pair<const char *, const char *>> & table,
                       std::string * mapped) {
        for (const auto & e : table) {
            size_t n = strlen(e.first);
            if (tail.compare(0, n, e.first) == 0 && tail.size() > n && tail[n] == '.') {
                *mapped = std::string(e.second) + tail.substr(n);
                return true;
            }
        }
        return false;
    };
    std::string rest, idx, tail, mapped;

    // language model
    if (name == "token_embd.weight") {
        out->push_back({ "model.embed_tokens.weight", -1 });
    } else if (name == "output.weight") {
        out->push_back({ "lm_head.weight", -1 });
    } else if (name == "output_norm.weight") {
        out->push_back({ "model.norm.weight", -1 });
    } else if (starts("blk.", &rest) && layer(rest, &idx, &tail)) {
        static const std::vector<std::pair<const char *, const char *>> lm = {
            { "attn_norm",   "input_layernorm"          },
            { "attn_q_norm", "self_attn.q_norm"         },
            { "attn_k_norm", "self_attn.k_norm"         },
            { "attn_q",      "self_attn.q_proj"         },
            { "attn_k",      "self_attn.k_proj"         },
            { "attn_v",      "self_attn.v_proj"         },
            { "attn_output", "self_attn.o_proj"         },
            { "ffn_norm",    "post_attention_layernorm" },
            { "ffn_gate",    "mlp.gate_proj"            },
            { "ffn_up",      "mlp.up_proj"              },
            { "ffn_down",    "mlp.down_proj"            },
        };
        if (map_tail(tail, lm, &mapped)) {
            out->push_back({ "model.layers." + idx + "." + mapped, -1 });
        }
    }
    // RVQ depth decoder
    else if (starts("depth.", &rest)) {
        static const std::vector<std::pair<const char *, const char *>> top = {
            { "proj",        "projection"       },
            { "pos_embd",    "pos_embedding"    },
            { "output_norm", "norm"             },
            { "audio_embd",  "audio_embeddings" },
        };
        static const std::vector<std::pair<const char *, const char *>> blk = {
            { "attn_norm",   "input_layernorm"          },
            { "attn_q",      "attn.to_q"                },
            { "attn_k",      "attn.to_k"                },
            { "attn_v",      "attn.to_v"                },
            { "attn_output", "attn.to_out"              },
            { "ffn_norm",    "post_attention_layernorm" },
            { "ffn_gate",    "gate_proj"                },
            { "ffn_up",      "up_proj"                  },
            { "ffn_down",    "down_proj"                },
        };
        std::string r2;
        if (map_tail(rest, top, &mapped)) {
            out->push_back({ mapped, -1 });
        } else if (rest.compare(0, 5, "head.") == 0) {
            out->push_back({ "audio_heads." + rest.substr(5), -1 });
        } else if (rest.compare(0, 4, "blk.") == 0 && layer(rest.substr(4), &idx, &tail) &&
                   map_tail(tail, blk, &mapped)) {
            out->push_back({ "layers." + idx + "." + mapped, -1 });
        }
    }
    // DiT
    else if (starts("dit.", &rest)) {
        static const std::vector<std::pair<const char *, const char *>> top = {
            { "preprocess_conv",  "preprocess_conv"     },
            { "postprocess_conv", "postprocess_conv"    },
            { "time_fourier",     "time_proj"           },
            { "time_embd.0",      "time_embed.linear_1" },
            { "time_embd.1",      "time_embed.linear_2" },
            { "proj_in",          "proj_in"             },
            { "proj_out",         "proj_out"            },
        };
        static const std::vector<std::pair<const char *, const char *>> blk = {
            { "attn_norm",   "norm1"         },
            { "attn_output", "attn.to_out.0" },
            { "ffn_norm",    "norm2"         },
            { "ffn_in",      "ff_in"         },
            { "ffn_out",     "ff_out"        },
        };
        if (map_tail(rest, top, &mapped)) {
            out->push_back({ mapped, -1 });
        } else if (rest.compare(0, 4, "blk.") == 0 && layer(rest.substr(4), &idx, &tail)) {
            std::string p = "transformer_blocks." + idx + ".";
            if (tail == "attn_qkv.weight") {
                out->push_back({ p + "attn.to_q.weight", 0 });
                out->push_back({ p + "attn.to_k.weight", 1 });
                out->push_back({ p + "attn.to_v.weight", 2 });
            } else if (map_tail(tail, blk, &mapped)) {
                out->push_back({ p + mapped, -1 });
            }
        }
    }
}

// Aliases for a file in the HOT-Step layout; a file already in the names the
// loaders use gets none
static bool gf_build_aliases(GGUFModel * gf) {
    int64_t n = gguf_get_n_tensors(gf->gguf);

    struct Plan {
        std::string          canonical;
        struct ggml_tensor * src;
        size_t               offset;
        int                  part;
    };

    std::vector<Plan> plan;
    for (int64_t i = 0; i < n; i++) {
        const char *                             tname = gguf_get_tensor_name(gf->gguf, i);
        std::vector<std::pair<std::string, int>> names;
        gf_hotstep_names(tname, &names);
        for (const auto & c : names) {
            if (gguf_find_tensor(gf->gguf, c.first.c_str()) < 0) {
                plan.push_back(
                    { c.first, ggml_get_tensor(gf->meta, tname), gguf_get_tensor_offset(gf->gguf, i), c.second });
            }
        }
    }
    if (plan.empty()) {
        return true;
    }
    struct ggml_init_params params = { ggml_tensor_overhead() * (plan.size() + 1), NULL, true };
    gf->alias_meta                 = ggml_init(params);
    if (!gf->alias_meta) {
        return false;
    }
    for (const auto & p : plan) {
        int64_t ne[4] = { 1, 1, 1, 1 };
        int     nd    = ggml_n_dims(p.src);
        for (int d = 0; d < nd; d++) {
            ne[d] = p.src->ne[d];
        }
        const uint8_t * data = gf->mapping + gf->data_offset + p.offset;
        if (p.part >= 0) {
            if (nd != 2 || ne[1] % 3 != 0) {
                fprintf(stderr, "[GGUF] FATAL: %s is not a fused qkv of three equal parts\n", ggml_get_name(p.src));
                return false;
            }
            ne[1] /= 3;
            data += (size_t) p.part * (size_t) ne[1] * ggml_row_size(p.src->type, ne[0]);
        }
        struct ggml_tensor * t = ggml_new_tensor(gf->alias_meta, p.src->type, nd, ne);
        ggml_set_name(t, p.canonical.c_str());
        gf->aliases[p.canonical] = { t, data };
    }
    fprintf(stderr, "[GGUF] HOT-Step layout: %zu tensors read under their MiniMax names\n", plan.size());
    return true;
}

// A tensor's descriptor by the name the loaders use, NULL when absent
static struct ggml_tensor * gf_meta(const GGUFModel & gf, const char * name) {
    struct ggml_tensor * t = ggml_get_tensor(gf.meta, name);
    if (t) {
        return t;
    }
    auto it = gf.aliases.find(name);
    return it == gf.aliases.end() ? NULL : it->second.meta;
}

static bool gf_load(GGUFModel * gf, const char * path) {
    *gf = {};

    // mmap the file
#ifdef _WIN32
    gf->fh = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (gf->fh == INVALID_HANDLE_VALUE) {
        fprintf(stderr, "[GGUF] Cannot open %s\n", path);
        return false;
    }
    LARGE_INTEGER li;
    GetFileSizeEx(gf->fh, &li);
    gf->file_size = (size_t) li.QuadPart;
    gf->mh        = CreateFileMappingA(gf->fh, NULL, PAGE_READONLY, 0, 0, NULL);
    if (!gf->mh) {
        CloseHandle(gf->fh);
        fprintf(stderr, "[GGUF] CreateFileMapping failed %s\n", path);
        return false;
    }
    gf->mapping = (uint8_t *) MapViewOfFile(gf->mh, FILE_MAP_READ, 0, 0, 0);
    if (!gf->mapping) {
        CloseHandle(gf->mh);
        CloseHandle(gf->fh);
        fprintf(stderr, "[GGUF] MapViewOfFile failed %s\n", path);
        return false;
    }
#else
    gf->fd = open(path, O_RDONLY);
    if (gf->fd < 0) {
        fprintf(stderr, "[GGUF] Cannot open %s\n", path);
        return false;
    }
    struct stat sb;
    fstat(gf->fd, &sb);
    gf->file_size = (size_t) sb.st_size;
    gf->mapping   = (uint8_t *) mmap(NULL, gf->file_size, PROT_READ, MAP_PRIVATE, gf->fd, 0);
    if (gf->mapping == MAP_FAILED) {
        close(gf->fd);
        gf->mapping = NULL;
        fprintf(stderr, "[GGUF] Mmap failed %s\n", path);
        return false;
    }
#endif

    // Parse GGUF header, create tensor metadata context
    struct ggml_context *   meta   = NULL;
    struct gguf_init_params params = { /*no_alloc=*/true, /*ctx=*/&meta };
    gf->gguf                       = gguf_init_from_file(path, params);
    if (!gf->gguf) {
        fprintf(stderr, "[GGUF] Failed to parse %s\n", path);
        gf_close(gf);
        return false;
    }
    gf->meta        = meta;
    gf->data_offset = gguf_get_data_offset(gf->gguf);

    int64_t n = gguf_get_n_tensors(gf->gguf);

    // Verify every tensor fits inside the mapped file. Catches truncated
    // downloads early with a clear message instead of a segfault deep in
    // cuMemcpyHtoDAsync when the backend reads past the mmap.
    for (int64_t i = 0; i < n; i++) {
        const char *         tname = gguf_get_tensor_name(gf->gguf, i);
        struct ggml_tensor * t     = ggml_get_tensor(gf->meta, tname);
        size_t               toff  = gguf_get_tensor_offset(gf->gguf, i);
        size_t               tsize = ggml_nbytes(t);
        size_t               end   = gf->data_offset + toff + tsize;
        if (end > gf->file_size) {
            fprintf(stderr,
                    "[GGUF] FATAL: '%s' is truncated or corrupt\n"
                    "[GGUF] FATAL: tensor '%s' needs bytes [%zu..%zu) but file is only %zu bytes\n"
                    "[GGUF] FATAL: re-download the file and verify its size or checksum\n",
                    path, tname, gf->data_offset + toff, end, gf->file_size);
            gf_close(gf);
            return false;
        }
    }

    if (!gf_build_aliases(gf)) {
        gf_close(gf);
        return false;
    }

    fprintf(stderr, "[GGUF] %s: %lld tensors, data at offset %zu\n", path, (long long) n, gf->data_offset);
    return true;
}

// Load a tensor from GGUF into the weight context.
// Returns ggml_tensor (not yet backed by memory; call wctx_alloc after all loads).
// Tensor shapes are already in ggml order (ne[0]=innermost).
static const void * gf_get_data(const GGUFModel & gf, const char * name);

static struct ggml_tensor * gf_load_tensor(WeightCtx *         wctx,
                                           const GGUFModel &   gf,
                                           const std::string & name,
                                           const int64_t *     shape_override  = nullptr,
                                           int                 n_dims_override = 0) {
    struct ggml_tensor * src = gf_meta(gf, name.c_str());
    if (!src) {
        fprintf(stderr, "[GGUF] FATAL: tensor '%s' not found\n", name.c_str());
        exit(1);
    }

    int     n_dims;
    int64_t ne[4] = { 1, 1, 1, 1 };

    if (shape_override && n_dims_override > 0) {
        n_dims = n_dims_override;
        for (int i = 0; i < n_dims; i++) {
            ne[i] = shape_override[i];
        }
    } else {
        n_dims = ggml_n_dims(src);
        for (int i = 0; i < n_dims; i++) {
            ne[i] = src->ne[i];
        }
    }

    struct ggml_tensor * tensor = ggml_new_tensor(wctx->ctx, src->type, n_dims, ne);
    ggml_set_name(tensor, name.c_str());

    const void * data   = gf_get_data(gf, name.c_str());
    size_t       nbytes = ggml_nbytes(src);

    wctx->pending.push_back({ tensor, data, nbytes, 0 });
    return tensor;
}

// Get raw pointer to tensor data in the mmapped file.
// Useful for CPU-side operations (e.g. bf16 embed lookup for lyrics).
// Returns NULL if not found.
static const void * gf_get_data(const GGUFModel & gf, const char * name) {
    int64_t idx = gguf_find_tensor(gf.gguf, name);
    if (idx < 0) {
        auto it = gf.aliases.find(name);
        return it == gf.aliases.end() ? NULL : it->second.data;
    }
    size_t offset = gguf_get_tensor_offset(gf.gguf, idx);
    return gf.mapping + gf.data_offset + offset;
}

// Read a whole tensor into a host F32 vector (F32 passthrough, BF16 converted).
static bool gf_host_f32(const GGUFModel & gf, const char * name, std::vector<float> & dst) {
    struct ggml_tensor * mt  = gf_meta(gf, name);
    const void *         raw = gf_get_data(gf, name);
    if (!mt || !raw) {
        return false;
    }
    size_t n = (size_t) ggml_nelements(mt);
    dst.resize(n);
    if (mt->type == GGML_TYPE_F32) {
        memcpy(dst.data(), raw, n * sizeof(float));
        return true;
    }
    const struct ggml_type_traits * traits = ggml_get_type_traits(mt->type);
    if (!traits->to_float) {
        return false;
    }
    traits->to_float(raw, dst.data(), (int64_t) n);
    return true;
}

// Load tensor, converting to F32 at load time (eliminates runtime cast nodes).
// Best for small tensors: norms [H], QK-norms [D], scale_shift_table [H,6], biases.
static struct ggml_tensor * gf_load_tensor_f32(WeightCtx * wctx, const GGUFModel & gf, const std::string & name) {
    struct ggml_tensor * src = gf_meta(gf, name.c_str());
    if (!src) {
        fprintf(stderr, "[GGUF] FATAL: tensor '%s' not found\n", name.c_str());
        exit(1);
    }
    int     n_dims = ggml_n_dims(src);
    int64_t ne[4]  = { 1, 1, 1, 1 };
    for (int i = 0; i < n_dims; i++) {
        ne[i] = src->ne[i];
    }

    // If already F32, just load normally
    if (src->type == GGML_TYPE_F32) {
        return gf_load_tensor(wctx, gf, name);
    }

    // Bail early on types without a dequantizer (before creating tensor in ctx)
    const struct ggml_type_traits * traits = ggml_get_type_traits(src->type);
    if (!traits->to_float) {
        fprintf(stderr, "[GGUF] WARNING: gf_load_tensor_f32 unsupported type %d for '%s', loading as-is\n", src->type,
                name.c_str());
        return gf_load_tensor(wctx, gf, name);
    }

    // Create F32 tensor
    struct ggml_tensor * tensor = ggml_new_tensor(wctx->ctx, GGML_TYPE_F32, n_dims, ne);
    ggml_set_name(tensor, name.c_str());

    // Convert data into staging buffer. unique_ptr keeps .get() stable even
    // when wctx->staging grows on subsequent calls.
    size_t  n    = ggml_nelements(src);
    auto    buf  = std::make_unique<float[]>(n);
    float * data = buf.get();

    const void * raw = gf_get_data(gf, name.c_str());

    traits->to_float(raw, data, (int64_t) n);

    wctx->pending.push_back({ tensor, data, n * sizeof(float), 0 });
    wctx->staging.push_back(std::move(buf));
    return tensor;
}

// Fuse Q, K, V projection weights into a single tensor [ne0, q_ne1 + k_ne1 + v_ne1].
// Works for any quantized type since quantization is per-row (along ne[0]).
// The fused tensor data is q rows || k rows || v rows (contiguous).
static struct ggml_tensor * gf_load_qkv_fused(WeightCtx *         wctx,
                                              const GGUFModel &   gf,
                                              const std::string & q_name,
                                              const std::string & k_name,
                                              const std::string & v_name) {
    struct ggml_tensor * q_src = gf_meta(gf, q_name.c_str());
    struct ggml_tensor * k_src = gf_meta(gf, k_name.c_str());
    struct ggml_tensor * v_src = gf_meta(gf, v_name.c_str());
    if (!q_src || !k_src || !v_src) {
        fprintf(stderr, "[GGUF] FATAL: QKV tensor not found: %s / %s / %s\n", q_name.c_str(), k_name.c_str(),
                v_name.c_str());
        exit(1);
    }
    // All must share ne[0] (input dim) and type - otherwise can't fuse
    GGML_ASSERT(q_src->ne[0] == k_src->ne[0] && k_src->ne[0] == v_src->ne[0]);
    if (q_src->type != k_src->type || k_src->type != v_src->type) {
        return NULL;  // caller should fall back to separate loads
    }

    int64_t              ne0       = q_src->ne[0];
    int64_t              fused_ne1 = q_src->ne[1] + k_src->ne[1] + v_src->ne[1];
    int64_t              ne[2]     = { ne0, fused_ne1 };
    struct ggml_tensor * fused     = ggml_new_tensor(wctx->ctx, q_src->type, 2, ne);

    size_t row_size = ggml_row_size(q_src->type, ne0);
    size_t q_bytes  = q_src->ne[1] * row_size;
    size_t k_bytes  = k_src->ne[1] * row_size;
    size_t v_bytes  = v_src->ne[1] * row_size;

    auto get_data = [&](const std::string & name) -> const void * {
        return gf_get_data(gf, name.c_str());
    };

    wctx->pending.push_back({ fused, get_data(q_name), q_bytes, 0 });
    wctx->pending.push_back({ fused, get_data(k_name), k_bytes, q_bytes });
    wctx->pending.push_back({ fused, get_data(v_name), v_bytes, q_bytes + k_bytes });
    return fused;
}

// Fuse two projection weights [ne0, a_ne1 + b_ne1] when types match.
// Returns NULL if types differ.
static struct ggml_tensor * gf_load_pair_fused(WeightCtx *         wctx,
                                               const GGUFModel &   gf,
                                               const std::string & a_name,
                                               const std::string & b_name) {
    struct ggml_tensor * a_src = gf_meta(gf, a_name.c_str());
    struct ggml_tensor * b_src = gf_meta(gf, b_name.c_str());
    if (!a_src || !b_src) {
        return NULL;
    }
    if (a_src->ne[0] != b_src->ne[0] || a_src->type != b_src->type) {
        return NULL;
    }

    int64_t              ne0   = a_src->ne[0];
    int64_t              ne[2] = { ne0, a_src->ne[1] + b_src->ne[1] };
    struct ggml_tensor * fused = ggml_new_tensor(wctx->ctx, a_src->type, 2, ne);

    size_t row_size = ggml_row_size(a_src->type, ne0);
    size_t a_bytes  = a_src->ne[1] * row_size;
    size_t b_bytes  = b_src->ne[1] * row_size;

    auto get_data = [&](const std::string & name) -> const void * {
        return gf_get_data(gf, name.c_str());
    };

    wctx->pending.push_back({ fused, get_data(a_name), a_bytes, 0 });
    wctx->pending.push_back({ fused, get_data(b_name), b_bytes, a_bytes });
    return fused;
}

// Read a string KV value (returns "" if not found)
static const char * gf_get_str(const GGUFModel & gf, const char * key) {
    int64_t idx = gguf_find_key(gf.gguf, key);
    if (idx < 0) {
        return "";
    }
    return gguf_get_val_str(gf.gguf, idx);
}
